name: Build and Release (Windows)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller==6.6.0

      - name: Build executable (PyInstaller)
        run: |
          pyinstaller --noconfirm --clean timerMQTT.spec
          if (!(Test-Path -Path 'dist/timerMQTT/timerMQTT.exe')) { throw 'Exe not found' }
          Copy-Item 'dist/timerMQTT/timerMQTT.exe' 'dist/timerMQTT.exe' -Force

      - name: Set version in installer.iss from tag
        shell: pwsh
        run: |
          $tag = "${{ github.ref_name }}"
          if ($tag.StartsWith('v')) { $version = $tag.Substring(1) } else { $version = $tag }
          $content = Get-Content 'installer.iss'
          $content = $content -replace '(#define\s+MyAppVersion\s+")([^"]+)(")', "`$1$version`$3"
          Set-Content 'installer.iss' $content

      - name: Build installer (Inno Setup)
        shell: pwsh
        run: |
          $iscc = 'C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe'
          if (!(Test-Path $iscc)) {
            choco install innosetup -y
          }
          & $iscc 'installer.iss'
          if (!(Test-Path -Path 'dist/timerMQTT-Setup.exe')) { throw 'Installer not found' }
          $tag = "${{ github.ref_name }}"
          $newName = "timerMQTT-Setup-" + $tag + ".exe"
          Rename-Item -Path 'dist/timerMQTT-Setup.exe' -NewName $newName -Force

      - name: Create portable ZIP
        shell: pwsh
        run: |
          $tag = "${{ github.ref_name }}"
          $zip = "dist/timerMQTT-portable-" + $tag + ".zip"
          if (Test-Path $zip) { Remove-Item $zip -Force }
          Compress-Archive -Path 'dist/timerMQTT/*' -DestinationPath $zip -CompressionLevel Optimal

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            dist/timerMQTT/timerMQTT.exe
            dist/timerMQTT.exe
            dist/timerMQTT-Setup-*.exe
            dist/timerMQTT-portable-*.zip

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/timerMQTT/timerMQTT.exe
            dist/timerMQTT-Setup-*.exe
            dist/timerMQTT-portable-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
